project:
  type: book
  output-dir: _book 

book:
  title: "Tax Microdata Benchmarking Review"
  author: 
    - "Don Boyd"
    - "Claude"
  date: today
  chapters:
    - index.qmd
    - todo.qmd
    - description.qmd
    - changes.qmd

format:
  html:cd 
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    toc-expand: 1    

execute:
  freeze: true