project:
  type: book
  output-dir: _book

book:
  title: "Tax Microdata Benchmarking Review"
  author: 
    - "Don Boyd"
    - "Claude"
  date: today
  chapters:
    - index.qmd
    - todo.qmd
    - description.qmd
    - qa.qmd
    - changes.qmd
    - git_commands.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: left
    toc-expand: 2

execute:
    freeze: auto
