# Introduction and goals

We want our TMD file to be as consistent as possible with what we know or project about the real world, for each year in question, for important variables. We try to achieve this by "targeting" important variables -- adjusting data file record weights, and adjusting certain data values, so that weighted sums of these variables hit or come close to values we expect.

## What kinds of targets do we want?

How do we define important variables? We have two major goals for the TMD file:

-  It should be useful and accurate for **tax policy revenue analysis**.
-  It should be useful and accurate for **tax policy distributional analysis**.

These two goals overlap considerably -- we cannot get tax revenue analysis right unless we have a data file that is reasonably consistent with the distribution of income, and we cannot get distributional analysis right unless that data file generates approximately the right amount of tax revenue.

In both cases, we want to target variables that are important for understanding current tax policy or for understanding policy alternatives of interest. [Example]

In certain cases we want to target values that are not found on tax returns. For example, we want our tax file to have information on *potential* deductions for state and local taxes, not actual deductions which have been capped since 2018. However, tax return values can be helpful in estimating *potential* deductions.

We do not have a formal method for defining precisely which variables to target and how, but based on our goals and knowledge our judgment leads us to target:

Aggregate items (weighted sums across all income ranges):

-  Total amounts for adjusted gross income and important income components including wages, interest, dividends, pensions, Social Security, capital gains, and business income. All are important for understanding total tax revenue and the distribution of revenue.
-  Numbers of returns that have nonzero values for these income items.
-  Total amounts for major potential itemized deductions including state and local taxes, contributions, mortgage interest, and medical expenses.
-  Numbers of returns that have nonzero values for these potential deductions.
-  Numbers of returns or individuals eligible for certain kinds of tax credits such as the child tax credit

For some of these items, we target totals by marital status.

Distributions:

- Number of returns by AGI range
- Total wages by AGI range
- Number of returns with nonzero wages by AGI range

We target the above items for expected tax filers. In addition, we target selected items for nonfilers.

## What years do we want to target?

We don't believe the forecast years are likely to be accurate if the data file is not accurate for the most recent year of history.

As of this writing, the most recent year with detailed distributional data released by the IRS is 2022. We use optimization methods to get the details right for 2022. We use simpler methods and less-detailed targets to extrapolate the data file to later years.
